import pytest
import time
from selenium.common.exceptions import TimeoutException
from pages.selectmac import Selectmac
from pages.buy import Buy

def test_select_mac(driver_chrome):
    driver_chrome.get("https://macbro.uz/")
    selectmac = Selectmac(driver_chrome)
    buy = Buy(driver_chrome)


    selectmac.click_all()
    time.sleep(5)
    selectmac.click_filtr9()
    time.sleep(5)
    selectmac.click_higttolow9()
    time.sleep(5)
    selectmac.click_openmac9()
    time.sleep(5)
    selectmac.click_addcard9()
    time.sleep(5)
    selectmac.click_close9()
    time.sleep(5)
    selectmac.click_goto_mac()
    time.sleep(1)
    selectmac.click_filtr()
    time.sleep(1)
    selectmac.click_higttolow()
    time.sleep(5)
    selectmac.click_openmac()
    time.sleep(1)
    selectmac.click_colorsilver()
    time.sleep(1)
    # selectmac.click_memmac()
    # time.sleep(1)
    selectmac.click_rammac()
    time.sleep(1)
    selectmac.click_addcard()
    time.sleep(1)
    selectmac.click_close()
    time.sleep(1)
    selectmac.click_iphone()
    time.sleep(3)
    # selectmac.click_filtr2()
    # time.sleep(3)
    # selectmac.higttolow2()
    # time.sleep(5)
    selectmac.click_openiphone()
    time.sleep(3)
    selectmac.click_addcard2()
    time.sleep(3)
    selectmac.click_close2()
    time.sleep(3)
    selectmac.click_akse()
    time.sleep(3)
    # selectmac.click_zaryadnik()
    # time.sleep(3)
    selectmac.click_filtr6()
    time.sleep(3)
    selectmac.click_higttolow6()
    time.sleep(3)
    selectmac.click_openzaryadnik()
    time.sleep(3)
    selectmac.click_addcard3()
    time.sleep(3)
    selectmac.click_close3()
    time.sleep(3)
    selectmac.click_dyson()
    time.sleep(3)
    selectmac.click_opendyson()
    time.sleep(3)
    selectmac.click_addcard4()
    time.sleep(3)
    selectmac.click_close4()
    time.sleep(3)
    selectmac.click_golden()
    time.sleep(3)
    selectmac.click_filtr3()
    time.sleep(3)
    selectmac.click_higttolow3()
    time.sleep(3)
    selectmac.click_open()
    time.sleep(3)
    selectmac.click_addcard5()
    time.sleep(3)
    # selectmac.click_delete()
    # time.sleep(3)
    # selectmac.click_delete2()
    # time.sleep(3)
    # selectmac.click_delete3()
    # time.sleep(3)
    # selectmac.click_delete4()
    # time.sleep(3)
    # selectmac.click_delete5()
    # time.sleep(3)
    selectmac.click_submit()
    time.sleep(3)
    selectmac.input_address("test@gmail.com")
    time.sleep(3)
    selectmac.click_deliver()
    time.sleep(3)
    selectmac.click_country()
    time.sleep(3)
    # selectmac.click_selectcountry()
    # selectmac.click_iname1()
    # time.sleep(3)
    # selectmac.input_iname("test")
    # time.sleep(3)
    # selectmac.click_isurname1()
    # time.sleep(3)
    # selectmac.input_isurname("test")
    # time.sleep(3)
    # selectmac.click_iaddress1()
    # time.sleep(3)
    # selectmac.input_iaddress("test")
    # time.sleep(3)
    # selectmac.click_icity1()
    # time.sleep(30)
    selectmac.input_icity("Урааа доставка бесплатно")
    time.sleep(30)







